const Jedlikmons =
[
    {
        'name': "Nitsubishi",
        'type': "Reál",
        'health': "120",
        'baseatk': "20",
        'baseatkDesc': "Deals 20 damage to enemy",
        'baseDef': "10",
        'DefDesc': "Increase defence by 50",
        'skill1': "Tiszta kód elve",
        'skill1Desc': "Add 40% damage buff for yourself",
        'sk1-type': 'dmgbuff',
        'sk1': '40',
        'sk1Status': "0",
        'limit1': '5',
        'skill2': "Salata Kód",
        'skill2Desc': "Add 40% damage debuff for enemy",
        'sk2-type': 'dmgdebuff',
        'sk2': '40',
        'sk2Status': "0",
        'limit2': '5',
        'skill3': "Chuck Norris Vicc",
        'skill3Desc': "Deals 2.5 times more than base damage",
        'sk3-type': 'dmg',
        'sk3': '2.5',
        'sk3Status': "0",
        'limit3': '1',
        'picture': '/pictures/laci1.png',
        'SmolPicture': '/pictures/laci.png',
    },
    {
        'name': "Liptákkopter",
        'type': "Reál",
        'health': "200",
        'baseDef': '0',
        'baseatk': "5",
        'baseatkDesc': "Deals 5 damage to enemy",
        'baseDef': "40",
        'DefDesc': "Increase defence by 80",
        'skill1': "OKTV papírok",
        'skill1Desc': "Add 2000% damage buff for yourself",
        'sk1-type': 'dmgbuff',
        'sk1': '2000',
        'sk1Status': "0",
        'limit1': '5',
        'skill2': "20 perc késés",
        'skill2Desc': "Add 50% damage debuff for enemy",
        'sk2-type': 'dmgdebuff',
        'sk2': '40',
        'sk2Status': "0",
        'limit2': '5',
        'skill3': "Excel dolgozat papíron",
        'skill3Desc': "Deals 5 times more than base damage",
        'sk3-type': 'dmg',
        'sk3': '5',
        'sk3Status': "0",
        'limit3': '5',
        'picture': '/pictures/LiptakKoter.png',
        'SmolPicture': '/pictures/LiptakKoter.png',
    }
];

export default Jedlikmons;