const Jedlikmons =
[
    {
        'name': "Nitsubishi",
        'type': "Reál",
        'health': "120",
        'baseatk': "20",
        'baseatkDesc': "Deals 20 damage to enemy",
        'baseDef': "10",
        'DefStat': "50",
        'DefDesc': "Increase defence by 50",
        'skill1': "Tiszta kód elve",
        'skill1Desc': "Add 40% damage buff for yourself",
        'sk1': '0.4',
        'skill2': "Salata Kód",
        'skill2Desc': "Add 40% damage debuff for enemy",
        'sk2': '0.4',
        'skill3': "Chuck Norris Vicc",
        'skill3Desc': "Deals 2.5 times more than base damage",
        'sk3': '2.5',
        'limit': "1",
        'picture': '/pictures/laci1.png',
        'SmolPicture': '/pictures/laci.png',
    },
    {
        'name': "Liptákkopter",
        'type': "Reál",
        'health': "200",
        'baseatk': "5",
        'baseatkDesc': "Deals 5 damage to enemy",
        'baseDef': "25",
        'DefDesc': "Increase defence by 80",
        'DefStat': "80",
        'skill1': "OKTV papírok",
        'skill1Desc': "Add 500% damage buff for yourself",
        'sk1': '5',
        'skill2': "20 perc késés",
        'skill2Desc': "Add 50% damage debuff for enemy",
        'sk2': '0.5',
        'skill3': "Excel dolgozat papíron",
        'skill3Desc': "Deals 4 times more than base damage",
        'sk3': '4',
        'limit': '3',
        'picture': '/pictures/LiptakKoter.png',
        'SmolPicture': '/pictures/LiptakKoter.png',
    },
    {
        'name': "Somesz",
        'type': "Mitikus",
        'health': "100",
        'baseatk': "50",
        'baseatkDesc': "Deals 50 damage to enemy",
        'baseDef': "0",
        'DefDesc': "Increase defence by 1",
        'DefStat': "1",
        'skill1': "Töri tanulás",
        'skill1Desc': "Add 1% damage buff for yourself",
        'sk1': '0.01',
        'skill2': "Időutazás",
        'skill2Desc': "Add 1% damage debuff for enemy",
        'sk2': '0.01',
        'skill3': "AK47",
        'skill3Desc': "Deals 2.5 times more than base damage",
        'sk3': '2.5',
        'limit': '3',
        'picture': '/pictures/AK-47.png',
        'SmolPicture': '/pictures/AK-47.png',
    },
    {
        'name': "Leverton Niggel",
        'type': "Bölcsész",
        'health': "250",
        'baseatk': "10",
        'baseatkDesc': "Deals 10 damage to enemy",
        'baseDef': "50",
        'DefDesc': "Increase defence by 75",
        'DefStat': "75",
        'skill1': "Roppant rendes tanár vagyok",
        'skill1Desc': "Add 100% damage buff for yourself",
        'sk1': '1',
        'skill2': "SHUT THE HELL UP",
        'skill2Desc': "Add 80% damage debuff for enemy",
        'sk2': '0.8',
        'skill3': "AK47",
        'skill3Desc': "Deals 1.5 times more than base damage",
        'sk3': '1.5',
        'limit': '10',
        'picture': '/pictures/AK-47.png',
        'SmolPicture': '/pictures/AK-47.png',
    }
];

export default Jedlikmons;